version: "3"
services:

  bbs:
    image: davestephens/enigma-bbs
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
